group foo

database FooBar

Foo -> Bar

group bar
  actor Bar
Bar -> Foo
end

Foo -> Bar : message
Bar->Foo:message boo
Bar->Foo: message boo
Bar->Foo:message boo
Foo <- Bar : message
Foo --> Bar : message
Foo <-- Bar : message
Foo->Bar
Foo <-- Bar : message

Foo -> Bar : message
Bar->Foo:message boo
Bar->Foo: message boo
Bar->Foo:message boo
Foo <- Bar : message
Foo --> Bar : message
Foo <-- Bar : message
Foo->Bar
Foo <-- Bar : message


Foo -> Bar : message

Bar->Foo:message boo
Bar->Foo: message boo
Bar->Foo:message boo



  Foo <- Bar : message
  Foo --> Bar : message
  Foo <-- Bar : message
  
  Foo->Bar
  Foo <-- Bar : message






end